[package]
name = "public-transport-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
rand = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"

[[bin]]
name = "pts" 
path = "src/main.rs"
